### ISSUE TITLE
java.lang.IllegalArgumentException: current must not be NaN

### ISSUE THREAD

**Issue by fuzhengyin** [imherrera/compose-video-player#3]
>FATAL EXCEPTION: main
                                                                                                    java.lang.IllegalArgumentException: current must not be NaN
                                                                                                    	at androidx.compose.ui.semantics.ProgressBarRangeInfo.<init>(SemanticsProperties.kt:489)
                                                                                                    	at androidx.compose.foundation.ProgressSemanticsKt$progressSemantics$1.invoke(ProgressSemantics.kt:52)
                                                                                                    	at androidx.compose.foundation.ProgressSemanticsKt$progressSemantics$1.invoke(ProgressSemantics.kt:50)
                                                                                                    	at androidx.compose.ui.semantics.SemanticsModifierCore.<init>(SemanticsModifier.kt:57)
                                                                                                    	at androidx.compose.ui.semantics.SemanticsModifierKt.semantics(SemanticsModifier.kt:110)
                                                                                                    	at androidx.compose.foundation.ProgressSemanticsKt.progressSemantics(ProgressSemantics.kt:50)
                                                                                                    	at androidx.compose.foundation.ProgressSemanticsKt.progressSemantics$default(ProgressSemantics.kt:41)
                                                                                                    	at androidx.compose.material.ProgressIndicatorKt.LinearProgressIndicator-eaDK9VM(ProgressIndicator.kt:80)
                                                                                                    	at com.imherrera.videoplayer.VideoPlayerControlKt.TimelineControl-8V94_ZQ(VideoPlayerControl.kt:191)
                                                                                                    	at com.imherrera.videoplayer.VideoPlayerControlKt.access$TimelineControl-8V94_ZQ(VideoPlayerControl.kt:1)
                                                                                                    	at com.imherrera.videoplayer.VideoPlayerControlKt$VideoPlayerControl$1.invoke(VideoPlayerControl.kt:53)
                                                                                                    	at com.imherrera.videoplayer.VideoPlayerControlKt$VideoPlayerControl$1.invoke(VideoPlayerControl.kt:34)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at com.imherrera.videoplayer.VideoPlayerControlKt.VideoPlayerControl-EMNEwkI(VideoPlayerControl.kt:34)

**Comment by taschmidt** [comment]
Getting this as well. Problem is duration is only assigned [here](https://github.com/imherrera/compose-video-player/blob/1fddb586f2a0bfb25f6448d5cf3a8aae5342d604/videoplayer/src/main/java/com/imherrera/videoplayer/VideoPlayerState.kt#L144) but in my case this is only called once when state is `STATE_BUFFERING` so duration is still zero. But there's no safety checks when dividing [here](https://github.com/imherrera/compose-video-player/blob/1fddb586f2a0bfb25f6448d5cf3a8aae5342d604/videoplayer/src/main/java/com/imherrera/videoplayer/VideoPlayerControl.kt#LL170C59-L170C59) to get the progress percentage.
